# Base stage for oven/bun
FROM oven/bun:1-slim AS base
WORKDIR /app

# Prune stage - extracts minimum needed packages for a specific app
FROM base AS pruner
ARG APP_NAME
ENV APP_NAME=$APP_NAME
COPY . .
# Run turbo prune to calculate the subset of the monorepo required
RUN bun x turbo prune --scope=$APP_NAME --docker

# Builder stage
FROM base AS builder
ARG APP_NAME
ENV APP_NAME=$APP_NAME

# Set build time variables
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# First install dependencies (this layer is cached until package.json/lock changes)
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lockb ./bun.lockb
# Install dependencies using frozen lockfile
RUN bun install --frozen-lockfile

# Copy the rest of the pruned source code
COPY --from=pruner /app/out/full/ .

# Generate database types
RUN bun --filter @inflow/db db:generate

# Build the specific app
RUN bun x turbo build --filter=$APP_NAME...

# Production stage
FROM base AS runner
ARG APP_NAME
ENV APP_NAME=$APP_NAME
WORKDIR /app

# Set environment to production
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create a non-root user
RUN groupadd --system --gid 1001 nodejs && \
    useradd --system --uid 1001 --gid nodejs --create-home --shell /bin/false nextjs

# Set permissions for the .next directory if it exists or needs to be created dynamically
# COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/public ./apps/${APP_NAME}/public
# COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/.next/standalone ./
# COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/.next/static ./apps/${APP_NAME}/.next/static

# Note: Instead of assuming /apps/${APP_NAME}/, we can copy the whole standalone root generated by next
# Turborepo standalone puts everything at the root of the project generally, or inside the specific app.
# The previous Dockerfile copied directly from /app/apps/${APP_NAME}/.next/standalone, we'll keep that path.

COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/public ./apps/${APP_NAME}/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/.next/static ./apps/${APP_NAME}/.next/static

USER nextjs
EXPOSE 3000

# Start the application using standalone server
CMD ["sh", "-c", "bun apps/${APP_NAME}/server.js"]
